node maximize.js ./src/ako.png ./dst/ako.png
node maximize.js ./src/aoki.png ./dst/aoki.png
node maximize.js ./src/b0.png ./dst/b0.png
node maximize.js ./src/b1.png ./dst/b1.png
node maximize.js ./src/b10.png ./dst/b10.png
node maximize.js ./src/b11.png ./dst/b11.png
node maximize.js ./src/b12.png ./dst/b12.png
node maximize.js ./src/b13.png ./dst/b13.png
node maximize.js ./src/b14.png ./dst/b14.png
node maximize.js ./src/b15.png ./dst/b15.png
node maximize.js ./src/b2.png ./dst/b2.png
node maximize.js ./src/b3.png ./dst/b3.png
node maximize.js ./src/b4.png ./dst/b4.png
node maximize.js ./src/b5.png ./dst/b5.png
node maximize.js ./src/b6.png ./dst/b6.png
node maximize.js ./src/b7.png ./dst/b7.png
node maximize.js ./src/b8.png ./dst/b8.png
node maximize.js ./src/b9.png ./dst/b9.png
node maximize.js ./src/cannon_big.png ./dst/cannon_big.png
node maximize.js ./src/cannon_big2.png ./dst/cannon_big2.png
node maximize.js ./src/cannon_middle.png ./dst/cannon_middle.png
node maximize.js ./src/cannon_middle2.png ./dst/cannon_middle2.png
node maximize.js ./src/cannon_small.png ./dst/cannon_small.png
node maximize.js ./src/exboss.png ./dst/exboss.png
node maximize.js ./src/fighter_big.png ./dst/fighter_big.png
node maximize.js ./src/fighter_big2.png ./dst/fighter_big2.png
node maximize.js ./src/fighter_middle.png ./dst/fighter_middle.png
node maximize.js ./src/fighter_middle2.png ./dst/fighter_middle2.png
node maximize.js ./src/fighter_small.png ./dst/fighter_small.png
node maximize.js ./src/heri1_1.png ./dst/heri1_1.png
node maximize.js ./src/heri1_2.png ./dst/heri1_2.png
node maximize.js ./src/heri2_1.png ./dst/heri2_1.png
node maximize.js ./src/heri2_2.png ./dst/heri2_2.png
node maximize.js ./src/hibiki.png ./dst/hibiki.png
node maximize.js ./src/higashi.png ./dst/higashi.png
node maximize.js ./src/hino.png ./dst/hino.png
node maximize.js ./src/honoka.png ./dst/honoka.png
node maximize.js ./src/hoshizora_t.png ./dst/hoshizora_t.png
node maximize.js ./src/hoshizora_y.png ./dst/hoshizora_y.png
node maximize.js ./src/hoshizora_y1.png ./dst/hoshizora_y1.png
node maximize.js ./src/hoshizora_y2.png ./dst/hoshizora_y2.png
node maximize.js ./src/kanade2.png ./dst/kanade2.png
node maximize.js ./src/kanade-cannon1-0.png ./dst/kanade-cannon1-0.png
node maximize.js ./src/kanade-cannon1-1.png ./dst/kanade-cannon1-1.png
node maximize.js ./src/kanade-cannon1-10.png ./dst/kanade-cannon1-10.png
node maximize.js ./src/kanade-cannon1-11.png ./dst/kanade-cannon1-11.png
node maximize.js ./src/kanade-cannon1-12.png ./dst/kanade-cannon1-12.png
node maximize.js ./src/kanade-cannon1-13.png ./dst/kanade-cannon1-13.png
node maximize.js ./src/kanade-cannon1-14.png ./dst/kanade-cannon1-14.png
node maximize.js ./src/kanade-cannon1-15.png ./dst/kanade-cannon1-15.png
node maximize.js ./src/kanade-cannon1-2.png ./dst/kanade-cannon1-2.png
node maximize.js ./src/kanade-cannon1-3.png ./dst/kanade-cannon1-3.png
node maximize.js ./src/kanade-cannon1-4.png ./dst/kanade-cannon1-4.png
node maximize.js ./src/kanade-cannon1-5.png ./dst/kanade-cannon1-5.png
node maximize.js ./src/kanade-cannon1-6.png ./dst/kanade-cannon1-6.png
node maximize.js ./src/kanade-cannon1-7.png ./dst/kanade-cannon1-7.png
node maximize.js ./src/kanade-cannon1-8.png ./dst/kanade-cannon1-8.png
node maximize.js ./src/kanade-cannon1-9.png ./dst/kanade-cannon1-9.png
node maximize.js ./src/kanade-cannon2-0.png ./dst/kanade-cannon2-0.png
node maximize.js ./src/kanade-cannon2-1.png ./dst/kanade-cannon2-1.png
node maximize.js ./src/kanade-cannon2-2.png ./dst/kanade-cannon2-2.png
node maximize.js ./src/kanade-cannon2-3.png ./dst/kanade-cannon2-3.png
node maximize.js ./src/kanade-cannon2-4.png ./dst/kanade-cannon2-4.png
node maximize.js ./src/kanade-cannon2-5.png ./dst/kanade-cannon2-5.png
node maximize.js ./src/kanade-cannon2-6.png ./dst/kanade-cannon2-6.png
node maximize.js ./src/kanade-cannon2-7.png ./dst/kanade-cannon2-7.png
node maximize.js ./src/madoka.png ./dst/madoka.png
node maximize.js ./src/mai.png ./dst/mai.png
node maximize.js ./src/mana.png ./dst/mana.png
node maximize.js ./src/milk.png ./dst/milk.png
node maximize.js ./src/momozono.png ./dst/momozono.png
node maximize.js ./src/nagisa.png ./dst/nagisa.png
node maximize.js ./src/nao.png ./dst/nao.png
node maximize.js ./src/pink.png ./dst/pink.png
node maximize.js ./src/pink2.png ./dst/pink2.png
node maximize.js ./src/rikka.png ./dst/rikka.png
node maximize.js ./src/saki.png ./dst/saki.png
node maximize.js ./src/t0.png ./dst/t0.png
node maximize.js ./src/t1.png ./dst/t1.png
node maximize.js ./src/t10.png ./dst/t10.png
node maximize.js ./src/t11.png ./dst/t11.png
node maximize.js ./src/t12.png ./dst/t12.png
node maximize.js ./src/t13.png ./dst/t13.png
node maximize.js ./src/t14.png ./dst/t14.png
node maximize.js ./src/t15.png ./dst/t15.png
node maximize.js ./src/t2.png ./dst/t2.png
node maximize.js ./src/t3.png ./dst/t3.png
node maximize.js ./src/t4.png ./dst/t4.png
node maximize.js ./src/t5.png ./dst/t5.png
node maximize.js ./src/t6.png ./dst/t6.png
node maximize.js ./src/t7.png ./dst/t7.png
node maximize.js ./src/t8.png ./dst/t8.png
node maximize.js ./src/t9.png ./dst/t9.png
node maximize.js ./src/tank_big.png ./dst/tank_big.png
node maximize.js ./src/tank_big2.png ./dst/tank_big2.png
node maximize.js ./src/tank_big3.png ./dst/tank_big3.png
node maximize.js ./src/tank_big4.png ./dst/tank_big4.png
node maximize.js ./src/urara.png ./dst/urara.png
node maximize.js ./src/yotsuba.png ./dst/yotsuba.png
